{"name": "test_edit_bio_with_exceeding_char_limit", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'find_element'", "trace": "self = <test.test_edit_bio.TestEditBio testMethod=test_edit_bio_with_exceeding_char_limit>\n\n    def setUp(self):\n        \"\"\"\n        Set up the test environment before each test.\n    \n        This method initializes the browser, loads the configuration,\n        and navigates to the specified URL.\n        \"\"\"\n        logging.info(\"------------------------------SETUP------------------------------\")\n    \n        self.browser = BrowserWrapper()\n        self.config = ConfigProvider.load_config_json()\n        self.driver = self.browser.get_driver(self.config[\"url\"])\n    \n        self.login_page = LoginPage(self.driver)\n>       self.login_page.login_flow(self.config[\"email\"], self.config[\"password\"])\n\ntest\\test_edit_bio.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nlogic\\login_page.py:62: in login_flow\n    home_page = HomePage(self._driver)\nlogic\\home_page.py:37: in __init__\n    self._min_price_input = WebDriverWait(self._driver, 10).until(\nC:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:96: in until\n    value = method(self._driver)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndriver = None\n\n    def _predicate(driver: WebDriverOrWebElement):\n>       return driver.find_element(*locator)\nE       AttributeError: 'NoneType' object has no attribute 'find_element'\n\nC:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:84: AttributeError"}, "description": "\n        Test editing the bio with invalid data (e.g., exceeding character limit).\n        ", "attachments": [{"name": "log", "source": "4ec5d4f8-4d39-49e4-aeb8-ede015f6e7fd-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c2beba73-f0e1-4cd3-85c2-0ec0bd8277ea-attachment.txt", "type": "text/plain"}], "start": 1721902199239, "stop": 1721902199992, "uuid": "174b48c6-8cf1-4392-9be1-13d900a6a1a9", "historyId": "ddbd9be87693152bc0770735c421ebd3", "testCaseId": "ddbd9be87693152bc0770735c421ebd3", "fullName": "test.test_edit_bio.TestEditBio#test_edit_bio_with_exceeding_char_limit", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_edit_bio"}, {"name": "subSuite", "value": "TestEditBio"}, {"name": "host", "value": "DESKTOP-IGNAR84"}, {"name": "thread", "value": "12556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_edit_bio"}]}